# Generated by Django 5.0.2 on 2024-09-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamateriaprima',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='users.proveedor'),
        ),
        migrations.AddField(
            model_name='entradamateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventory.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimalote',
            name='lote_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='inventory.loteproducto'),
        ),
        migrations.AddField(
            model_name='materiaprimalote',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materiaprima'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto'),
        ),
    ]
